INSERT INTO Album (nomAlbum,nomArtist,Annee,Label,imagePath) VALUES
('XX','The xx',2020,'truc','/static/images/album/The xx/XX.jpg'),
('We Started Nothing','The Ting Tings',5500,'truc','/static/images/album/The Ting Tings/We Started Nothing.jpg'),
('Hybrid Theory','Linkin Park',4500,'yolo','/static/images/album/Linkin Park/Hybrid Theory.jpg'),
('Minutes to Midnight','Linkin Park',9586,'truc','/static/images/album/Linkin Park/Minutes to Midnight.jpg'),
('Loco con da Frenchy Talkin','Shaka Ponk',5252,'truc','/static/images/album/Shaka Ponk/Loco con da Frenchy Talkin.jpg'),
('Bad Porn Movie Trax','Shaka Ponk',8459,'truc','/static/images/album/Shaka Ponk/Bad Porn Movie Trax.jpg'),
('All or Nothing','The Subways',7589,'truc','/static/images/album/The Subways/All or Nothing.jpg'),
('Comme Des Enfants','Coeur De Pirate',6589,'truc','/static/images/album/Coeur De Pirate/Comme Des Enfants.jpg'),
('Man on the Moon The End of Day','Kid cudi',7896,'truc','/static/images/album/Kid cudi/Man on the Moon The End of Day.jpg'),
('Sweep of Days','Blue Foundation',5658,'truc','/static/images/album/Blue Foundation/Sweep of Days.jpg'),
('Creatures','Rone',8958,'truc','/static/images/album/Rone/Creatures.jpg'),
('Live in Hyde Park','Red Hot Chili Peppers',4859,'truc','/static/images/album/Red Hot Chili Peppers/Live in Hyde Park.jpg'),
('Conditions','The Temper Trap',8585,'truc','/static/images/album/The Temper Trap/Conditions.jpg'),
('How We Are','Bombay Bicycle Club',8888,'truc','/static/images/album/Bombay Bicycle Club/How We Are.jpg');
