INSERT INTO Music(nomAlbum,titre,musicPath,caract) VALUES
('XX','Crystalised','/static/musiques/The xx/XX/Crystalised.mp3','lent indie rock'),
('We Started Nothing','We Walk','/static/musiques/The Ting Tings/We Started Nothing/We Walk.mp3','piano indie pop rythme'),
('Hybrid Theory','In The End','/static/musiques/Linkin Park/Hybrid Theory/In The End.mp3','metal nu rap rock alternatif electro'),
('Hybrid Theory','My December','/static/musiques/Linkin Park/Hybrid Theory/My December.mp3','metal nu rap rock alternatif piano lent blues'),
('Minutes to Midnight','What I ve done','/static/musiques/Linkin Park/Minutes to Midnight/What I ve done.mp3','metal nu rap rock riff alternatif'),
('Loco con da Frenchy Talkin','Fonk me','/static/musiques/Shaka Ponk/Loco con da Frenchy Talkin/Fonk me.mp3','electro rock funk rythme french'),
('Bad Porn Movie Trax','French touch puta madre','/static/musiques/Shaka Ponk/Bad Porn Movie Trax/French touch puta madre.mp3','electro rock funk rythme french'),
('All or Nothing','Lost Boy','/static/musiques/The Subways/All or Nothing/Lost Boy.mp3','punk garage rock uk folk clean'),
('Comme Des Enfants','Comme Des Enfants','/static/musiques/Coeur De Pirate/Comme Des Enfants/Comme Des Enfants.mp3','piano lent french folk pop electro'),
('Man on the Moon The End of Day','heart of lion','/static/musiques/Kid cudi/Man on the Moon The End of Day/heart of lion.mp3','hip hop rap underground rythme us'),
('Sweep of Days','Bonfires','/static/musiques/Blue Foundation/Sweep of Days/Bonfires.mp3','electro lent dubstep'),
('Creatures','Intro','/static/musiques/Rone/Creatures/Intro.mp3','electro french french-touch boilerroom'),
('Live in Hyde Park','Fortune Faded','/static/musiques/Red Hot Chili Peppers/Live in Hyde Park/Fortune Faded.mp3','rock funk funkrock rythme guitar '),
('Conditions','Science Of Fear','/static/musiques/The Temper Trap/Conditions/Science Of Fear.mp3','rock alternatif rythme riff'),
('How We Are','Ghost','/static/musiques/Bombay Bicycle Club/How We Are/Ghost.mp3','guitar indie rock uk rythme clean'),
('How We Are','How Are We','/static/musiques/Bombay Bicycle Club/How We Are/How Are We.mp3','rock indie uk guitar');
